name: EpicHeads
description: EpicHeads
main: com.songoda.epicheads.EpicHeads
version: maven-version-number
author: Songoda
api-version: 1.13
commands:
  EpicHeads:
    description: View information on this plugin.
    default: true
    aliases: [ehe, heads, head]
    usage: /epicheads