name: DeluxeHeads
main: nl.marido.deluxeheads.DeluxeHeads
description: Enhance your server with over 17,000 awesome unique heads with amazing features.
author: Marido
version: 2.1.8
api-version: 1.13
softdepend: [Vault, PlayerPoints, BlockStore]
loadbefore: [DeluxeMenus]
permissions:
   deluxeheads.reload:
      description: 'Reload the config files'
      default: op
   deluxeheads.menu:
      description: 'Open the head menu'
      default: op
   deluxeheads.get:
      description: 'Use the /deluxeheads get <name> command'
      default: op
   deluxeheads.search:
      description: 'Use the /deluxeheads search <search query> command'
      default: op
   deluxeheads.hat:
      description: 'Use the /deluxeheads hat command'
      default: true
   deluxeheads.add:
      description: 'Add heads to the cache'
      default: op
   deluxeheads.hand:
      description: 'Add heads from your hand into the cache'
      default: op
   deluxeheads.random:
      description: 'Get a random head from the cache'
      default: op
   deluxeheads.remove:
      description: 'Remove heads from the cache'
      default: op
   deluxeheads.rename:
      description: 'Rename heads in the cache'
      default: op
   deluxeheads.id:
      description: 'Get a heads id'
      default: op
   deluxeheads.give:
      description: 'Give players heads'
      default: op
   deluxeheads.cost:
      description: 'Set heads costs'
      default: op
   deluxeheads.category-cost:
      description: 'Set heads costs by category'
      default: op
   deluxeheads.bypasscost:
      description: 'Bypass paying for heads'
      default: op
   deluxeheads.category.*:
      description: 'Permission for all categories'
      default: true
   deluxeheads.item-eco:
      description: 'Permission to set, get and give the economy item'
      default: op